# Generated by Django 5.2.4 on 2025-07-10 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
